
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohbhidtcnoxyztggspdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oYmhpZHRjbm94eXp0Z2dzcGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NDUyMzUsImV4cCI6MjA1NjMyMTIzNX0.LveCARcxhE-Z7Tt07Qe2A6idhiY9zIpS0m8Pn7RFHy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// クライアントオプションを追加してパフォーマンスと挙動を改善
const supabaseOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
      'X-Client-Info': 'tech-talks-exchange-app'
    },
  }
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  supabaseOptions
);
